### ISSUE TITLE
ERROR: Field 'metafields' is missing required arguments: identifiers

### ISSUE THREAD

**Issue by SaberMage** [BuilderIO/builder-shopify-hydrogen#1]
I have performed all setup steps as per the readme. Running node v16.13.2. When I try to load the page in the builder.io editor or on its own, I receive the error message above. I haven't been able to find any existing information or other cases pertaining to this error.

Please advise. Thanks!

![image](https://user-images.githubusercontent.com/1035144/174884973-23f8759f-2df2-488e-84e5-8be7f605e5ef.png)

**Comment by patricklai8k** [comment]
You may need to downgrade your storeFrontAPI version to 2022-04 from unstable.

**Comment by sebinievas** [comment]
@SaberMage this is happening because Shopify updated their API in 2022-07. You now should explicitly define the metafield you're intending to fetch. For example to fetch the namespace `bleep` and key `bloop` you can use:

```js
...
myBleepBloop: metafield(namespace: "bleep", key: "bloop") {
  value
}
...
```
in your graphQL
