### ISSUE TITLE
BuilderComponent Hydrogen SSR

### ISSUE THREAD

**Issue by guibovo** [BuilderIO/builder-shopify-hydrogen#2]
I'm trying to use the BuilderComponent as SSR so I can be able to fetch Shopify Product data from the handle in a Builder Custom Component.

I've seen this issue but I was not able to find any follow-up on this. Is there any update on it?

https://github.com/Shopify/hydrogen/issues/631

**Comment by steve8708** [comment]
ah yes, the problem here is that server components can not be loaded inside client components. `getAsyncProps` is how people today support components that need data within Builder - lmk if [this](https://github.com/BuilderIO/builder/tree/main/packages/utils#getasyncprops) helps explain well enough

**Comment by steve8708** [comment]
Oh no this is totally reusable, the util just finds _when_ a component is used, and any time it's used in any place it'll bring in the data it needs, so the component is exactly like you describe: a custom component people can drop anywhere in Builder and it'll fetch the data itself when/where used automatically

Adding @teleaziz to help explain in a bit more detail

**Comment by teleaziz** [comment]
Hi @guibovo , we have it on our roadmap to add full react server components support so you can fetch data within the component code, for now you can bake the required data into the builder json, which will get passed to the component as a prop, so for this case:
https://github.com/BuilderIO/builder-shopify-hydrogen/blob/main/src/pages/landing/%5Bhandle%5D.server.jsx#L11-L13

```

const content =  await builder
      .get(MODEL_NAME, {
        userAttributes: {
          urlPath: props.pathname,
        },
      })
      .promise();

// bake async data into the json passed to the BuilderComponent

await getAsyncProps(content, {
     async ProductCard(props) {
        if (props.productId && typeof props.productId === 'string') {
          const productObject = await fetchProductById();
          return {
            productObject,
          }
        }
     },
})

return content;

```

Now in your custom component you'll get the `props.productObject` pre-fetched when rendering

For a more concrete examples recommend checking our [Next.js + Shopify starter](https://github.com/BuilderIO/nextjs-shopify), especially this [file](https://github.com/BuilderIO/nextjs-shopify/blob/master/lib/resolve-builder-content.ts#L24) where we fetch all the custom components's required data
Let me know if you have any questions!

**Comment by guibovo** [comment]
Thanks a lot @teleaziz I was able to fetch my data! I'm now playing around with NextJS too, have followed what you did to apply this on my project. The only thing I'm facing now, is that on PREVIEW and on EDITOR the data is not passed as props, altho it is being fetched.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3513557/183040074-df4e6121-20a3-4a27-8544-621827c5aa95.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3513557/183040118-d6a5cc85-f5a8-47ec-9f63-9e79e3e16a9c.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3513557/183040245-08411ffa-8b13-4b8d-8be2-65c5947ce84b.png">

**Comment by otavioserraamyris** [comment]
Hello guys! I am struggling to create the routing in my project, in which I am using Hydrogen with buider.io. Has anyone already tried that stack? We have a considerable e-commerce on Shopify and we're considering this stack for us

**Comment by guibovo** [comment]
> Hi @guibovo , we have it on our roadmap to add full react server components support so you can fetch data within the component code, for now you can bake the required data into the builder json, which will get passed to the component as a prop, so for this case: https://github.com/BuilderIO/builder-shopify-hydrogen/blob/main/src/pages/landing/%5Bhandle%5D.server.jsx#L11-L13
> 
> ```ts
> const content =  await builder
>       .get(MODEL_NAME, {
>         userAttributes: {
>           urlPath: props.pathname,
>         },
>       })
>       .promise();
> 
> // bake async data into the json passed to the BuilderComponent
> 
> await getAsyncProps(content, {
>      async ProductCard(props) {
>         if (props.productId && typeof props.productId === 'string') {
>           const productObject = await fetchProductById();
>           return {
>             productObject,
>           }
>         }
>      },
> })
> 
> return content;
> ```
> 
> Now in your custom component you'll get the `props.productObject` pre-fetched when rendering
> 
> For a more concrete examples recommend checking our [Next.js + Shopify starter](https://github.com/BuilderIO/nextjs-shopify), especially this [file](https://github.com/BuilderIO/nextjs-shopify/blob/master/lib/resolve-builder-content.ts#L24) where we fetch all the custom components's required data Let me know if you have any questions!

This worked perfectly on NextJS Commerce, however I just heard that the company is moving with Hydrogen, in which I'm struggling to be able to do the same I did on Next.

With that in mind, perhaps you have nay functional example with Hydrogen?
